spring:
  application:
    name: mfstudio

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mfstudio}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: none