spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mfstudio
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true